mysite/food/urls.py
from django.urls import path
from . import views

app_name = "food"
urlpatterns = [
    path("", views.IndexClassView.as_view(), name="index"),
    path("item/", views.item, name="item"),
    # food/1
    path('<int:pk>/', views.FoodDetail.as_view(), name="detail"),
    # add items
    path('add/', views.CreateItem.as_view(), name="create-item"),
    path('update/<int:id>/', views.update_item, name="update_item"),
    path('delete-item/<int:id>/', views.delete_item, name="delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", include("users.urls")),
    path("login/", authentication_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", authentication_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path("profile/", user_views.profilepage, name="profile"),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.register, name="register"),
]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):

    # explicitly defining the string representation of this model
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=200, default='https://i0.wp.com/servedcatering.com/wp-content/uploads/2021/05/menu-item-placeholder.png?ssl=1')

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
# creates a class for each form we create here
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "item_image"]

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

mysite/food/views.py
from django.http import HttpResponse
from .models import Item
from django.shortcuts import render, redirect
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
# def index(request):
#     item_list = Item.objects.all()
#
#     context = {
#         'item_list': item_list,
#     }
#     return render(request, "food/index.html", context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse("<h1>his is the item view</h1>")


# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item,
#     }
#     return render(request, "food/detail.html", context)


class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


# creating a class based view for the create item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = "food/item-form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        
        return super().form_valid(form)


# def create_item(request):
#     form = ItemForm(request.POST or None)
#
#     if form.is_valid():
#         form.save()
#         return redirect("food:index")
#
#     return render(request, "food/item-form.html", {'form': form})


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")

    return render(request, "food/item-form.html", {'form': form, 'item': item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect("food:index")

    return render(request, "food/item-delete.html", {'item': item})

mysite/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        # checking the validity of data in form
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {'form': form})

@login_required
def profilepage(request):
    return render(request, "users/profile.html")

mysite/food/templates/food/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>

        <div class="navbar">
            <ul>
                <a href="{% url 'food:create-item'%}" class="nav-item navbar-link">Add Item </a>
                <a href="#" class="nav-item navbar-link">Delete Item </a>
                <a href="#" class="nav-item navbar-link">View Item </a>
                {% if user.is_authenticated %}
                    <a href = "{% url 'logout' %}"> Logout </a>
                    <a href= "{% url 'profile' %}">Profile</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" alt="" class="card" height="300px" width="400px"/>
        </div>

        <div class="col-md-6">
            <h1>{{object.item_name}} </h1>
            <h2> {{object.item_desc}} </h2>
            <h3> {{object.item_price}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/food/templates/food/index.html
{% extends "food/base.html" %}
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">

<body>
    {% block body %}
        {%for item in item_list %}
            <div class="row">
                <div class="col-md-3 offset-md-2 padding">
                    <img src="{{ item.item_image }}" alt="" class="card" height="225px" width="320px"/>
                </div>
                <div class="col-md-4">
                    <h3>{{ item.item_name }}</h3>
                    <h5> {{ item.item_desc }}</h5>
                    <h6> ${{ item.item_price }}</h6>
                    <h6> {{ item.user_name }}</h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
                </div>
            </div>
        {% endfor %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-3">
            <div class="card-header text-white bg-info">
                <div class="card-title">
                    Login
                </div>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class = 'form-group'>
                            {{ field.name }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class ="btn-info" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/users/templates/users/logout.html
<h1> You've been logged out </h1>

mysite/users/templates/users/profile.html
<h1> {{ user.username }} </h1>
<img src="{{ user.profile.image.url }}" height="200px" width="300px">

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-3">
            <div class="card-header text-white bg-info">
                <div class="card-title">
                    Register
                </div>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class="btn-info" type="submit">SignUp</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}